# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config --global user.name "Nikolay"
    git config --global user.email "shadowapril12@gmail.com"
    git checkout remotes/origin/CountChars2
    git cherry-pick e3f76e731e24e34ba44a8de9dc38ffd5f031a2fc
  displayName: 'Trying to cherry-pick'
